language: node_js
node_js:
  - "stable"
script:
  - npm install webdriverio --save-dev
  - curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
  - java -jar selenium-server-standalone-3.5.3.jar &
  - ./node_modules/.bin/wdio wdio.conf.js
